### PR TITLE
registration and login fully functional and styling applied

### PR DESCRIPTION
**Pull request by MandasK**
Please delete options that are not relevant.

 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)

Testing Instructions
fetch branch to test--can now login or register and receive alert errors is info is in use or incorrect,
also styling should all appear

Checklist:
- [x] My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [x]  My changes generate no new warnings or errors
- [x]  I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Tlane77** [comment]
Looks good

**Comment by Tlane77** [comment]
looks Great!

**Review by BeatleyTQD — APPROVED** [review]
Looks good!

**Review by tylerghilliard94 — APPROVED** [review]
This looks good

**Pull request merged**
